version: '3'
services:
    redis:
        image: redis:latest
        container_name: container_name-redis
        ports:
            - 6385:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]