apiVersion: v1
kind: Service
metadata:
  name: jcam98-test-flask-service
  labels:
    username: jcam98
    env: test
    app: jcam98-test-flask
spec:
  type: ClusterIP
  selector:
    app: jcam98-test-flask
  ports:
  - name: jcam98-test-flask
    port: 5000
    targetPort: 5000