apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcam98-test-flask
  labels:
    app: jcam98-test-flask
    username: jcam98
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jcam98-test-flask
  template:
    metadata:
      labels:
        username: jcam98
        env: test
        app: jcam98-test-flask
    spec:
      containers:
        - name: jcam98-test-flask
          imagePullPolicy: Always
          image: jcam989/animals
          env:
            - name: "Flask_App"
              value: app.py
            - name: REDIS_IP
              value: 10.97.112.162
          ports:
            - name: http
              containerPort: 5000


