apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcam98-test-pvc
  labels:
    username: jcam98
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
