apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcam989-prod-worker
  labels:
    app: jcam989-prod-worker
    username: jcam989
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jcam989-prod-worker
  template:
    metadata:
      labels:
        username: jcam989
        env: prod
        app: jcam989-prod-worker
    spec:
      containers:
        - name: jcam989-prod-worker
          imagePullPolicy: Always
          image: jcam989/final-project-prod:latest
          # command: ["sleep", "99999"]
          command: ["python", "worker.py"]
          env:
            - name: REDIS_IP
              value: 10.104.54.244  
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
