apiVersion: v1
kind: Service
metadata:
  name: jcam989-prod-redis-service
spec:
  type: ClusterIP 
  selector: 
    app: jcam989-prod-redis
  ports: 
  - name: jcam989-prod-redis-service
    port: 6379
    targetPort: 6379