apiVersion: v1
kind: Service
metadata:
  name: jcam989-prod-flask-service
  labels:
    username: jcam989
    env: prod
    app: jcam989-prod-flask
spec:
  type: ClusterIP
  selector:
    app: jcam989-prod-flask
  ports:
  - name: jcam989-prod-flask
    port: 5000
    targetPort: 5000

