apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcam989-prod-pvc
  labels:
    username: jcam989
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi